- .gitignore
- database/migrations/2018_10_09_182447_create_table_events_and_subevents.php
- database/migrations/2018_10_09_190000_create_table_people.php
- database/migrations/2018_10_09_190001_create_table_invitation.php
> Issues de Banco de Dados

- app/Data/Models/Invitation.php
- app/Data/Repositories/Invitations.php
> Invitation - Code and UUID

- app/Data/Models/Sector.php
- app/Data/Models/SubEvent.php
- app/Data/Repositories/Sectors.php
- app/Http/Controllers/Api/Sectors.php
- app/Http/Requests/SectorStore.php
- app/Http/Requests/SectorUpdate.php
- database/migrations/2018_11_07_154032_create_table_sectors.php
- public/js/app.js
- public/mix-manifest.json
- resources/js/store/modules/environment.js
- resources/js/store/modules/subEvents.js
- resources/js/views/SubEventsForm.vue
- routes/web.php
> Added sector to SubEventForm

- app/Data/Models/SubEvent.php
- app/Data/Repositories/SubEvents.php
- app/Http/Controllers/Api/SubEvents.php
- app/Http/Requests/SubEventStore.php
- app/Http/Requests/SubEventUpdate.php
- database/migrations/2018_10_09_182447_create_table_events_and_subevents.php
- public/mix-manifest.json
- resources/js/routes.js
- resources/js/store/modules/environment.js
- resources/js/store/modules/subEvents.js
- resources/js/views/Events.vue
- resources/js/views/SubEventsForm.vue
- routes/web.php
> Erro ao criar sub evento && Associar um subEvento a outro && Finalizar evento

- app/Data/Models/Event.php
- app/Data/Models/Invitation.php
- app/Data/Models/SubEvent.php
- app/Data/Repositories/Events.php
- app/Data/Repositories/Invitations.php
- app/Data/Repositories/Repository.php
- app/Data/Repositories/SubEvents.php
- app/Data/Repositories/Traits/DataProcessing.php
- app/Http/Controllers/Api/SubEvents.php
- app/Http/Controllers/HomeController.php
- public/css/app.css
- public/mix-manifest.json
- resources/js/components/app/AddressForm.vue
- resources/js/store/modules/mixins/actions.js
- resources/js/store/modules/subEventsDashBoard.js
- resources/js/views/Events.vue
- routes/web.php
Add pending column to invitations
> Show pending data in invitations

- app/Services/Environment/Service.php
- public/css/app.css
- public/mix-manifest.json
- resources/js/views/PhoneBook.vue
Recarregar dados de pessoa que foi gravada
#197
> Recarregar dados de pessoa que foi gravada

- app/Data/Models/PersonInstitution.php
> Fixed Advisors filter search

- app/Http/Kernel.php
- app/Http/Middleware/MustBeAppUser.php
- public/mix-manifest.json
- resources/js/store/modules/institutions.js
- resources/js/views/InstitutionsForm.vue
- resources/views/errors/403.blade.php
- resources/views/errors/404.blade.php
- resources/views/errors/500.blade.php
- resources/views/layouts/errors.blade.php
- routes/web.php
> To use app, the user must have read permission

- app/Data/Models/Institution.php
- app/Data/Models/Person.php
- app/Data/Models/PersonInstitution.php
- app/Data/Models/Role.php
- app/Data/Repositories/People.php
- app/Data/Repositories/Repository.php
- app/Data/Scopes/CurrentClient.php
- public/mix-manifest.json
- resources/js/components/app/Select.vue
- resources/js/store/modules/mixins/mutations.js
- resources/js/store/modules/mixins/states.js
- resources/js/store/modules/people.js
- resources/js/views/People.vue
- resources/js/views/PhoneBook.vue
> Revert "Institution and Roles filter in People"

- public/mix-manifest.json
- resources/js/components/app/MarkdownTextArea.vue
- resources/js/views/SubEventsForm.vue
> Added Markdown textareas

- app/Data/Models/Invitation.php
- app/Data/Repositories/Invitations.php
- app/Events/InvitationRejected.php
- app/Listeners/SendRejection.php
- app/Mail/Rejection.php
- app/Notifications/SendRejection.php
- app/Providers/EventServiceProvider.php
- resources/views/emails/rejection.blade.php
Ao declinar enviar e-mail sentindo muito
Enviar convites
#121
> Ao declinar enviar e-mail sentindo muito - Enviar convites #121

- app/Data/Models/PersonInstitution.php
- public/mix-manifest.json
Lista de convidáveis está na ordem errada
#350
> Lista de convidáveis está na ordem errada #350

- database/migrations/2018_12_04_114425_update_passeio_completo.php
> Remover 'Social' do traje 'Passeio completo'

- public/mix-manifest.json
- resources/js/views/Events.vue
>  Ajuste nas mensagens de confirmação de envio de convite e de credenciais.

- package-lock.json
- public/mix-manifest.json
- resources/js/support/helpers.js
- resources/js/views/mixins/people.js
Ajustes na Issue
#491
[Está fazendo requisições demais via pesquisa de pessoa]
> Ajustes na Issue #491 [Está fazendo requisições demais via pesquisa de pessoa]

- app/Data/Repositories/Invitations.php
- package-lock.json
- public/mix-manifest.json
- resources/js/views/Events.vue
> Added decline filter

- app/Data/Models/Invitation.php
- app/Http/Requests/BaseContact.php
- app/Http/Requests/ContactStore.php
- app/Http/Requests/ContactUpdate.php
- database/migrations/2018_12_12_102821_trim_contacts.php
- resources/views/emails/credential.blade.php
> Trim contacts

- app/Data/Models/User.php
- app/Http/Controllers/Admin/Home.php
Adicionado a coluna client_id nas tabelas: SubEvents, Institutions e Categories
> Menu Select para Troca de Sistemas (Cerimonial e Forum)

- app/Data/Models/Invitation.php
- app/Data/Repositories/Invitations.php
> Send one thanks email for each sub-event

- app/Data/Models/Address.php
- app/Data/Repositories/Addresses.php
- app/Data/Repositories/Repository.php
- app/Data/Repositories/Traits/AddressesTraits.php
- app/Events/AddressUpdated.php
- app/Events/AddressesChanged.php
- app/Http/Controllers/Api/Addresses.php
- app/Http/Controllers/Api/SubEvents.php
- resources/js/store/modules/environment.js
- resources/js/store/modules/subEvents.js
- resources/js/store/store.js
- resources/js/views/SubEventsForm.vue
- routes/auth/api/addresses.php
- routes/auth/api/events.php
Ao criar subevento os endereços estão repetindo #709
> Ao criar subevento os endereços estão repetindo #709

- resources/js/views/AdvisorContactsForm.vue
- resources/js/views/AdvisorsForm.vue
- resources/js/views/CategoriesForm.vue
- resources/js/views/CategorizablesForm.vue
- resources/js/views/ChangeInstitutionForm.vue
- resources/js/views/ContactTypesForm.vue
- resources/js/views/ContactsForm.vue
- resources/js/views/CostumesForm.vue
- resources/js/views/EventsForm.vue
- resources/js/views/InstitutionsForm.vue
- resources/js/views/InviteForm.vue
- resources/js/views/PeopleForm.vue
- resources/js/views/PersonInstitutionsAddressesForm.vue
- resources/js/views/PersonInstitutionsForm.vue
- resources/js/views/RolesForm.vue
- resources/js/views/SectorForm.vue
- resources/js/views/SubEventsForm.vue
- resources/js/views/TopicsForm.vue
- resources/js/views/TopicsableForm.vue
> Added permissions for save button in forms

- app/Data/Repositories/Dashboard.php
- resources/js/components/app/ContactField.vue
- resources/js/components/app/MarkdownTextArea.vue
- resources/js/components/app/Pagination.vue
- resources/js/components/app/RoleFilterForPerson.vue
- resources/js/components/app/UploadFile.vue
- resources/js/views/PhoneBook.vue
> Define returnArray and Prettier changes

- app/Data/Repositories/Traits/PeopleExport.php
- app/Services/Authorization.php
> Fix export
